version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 5433:1433
  webapplication3:
    image: webapplication3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'ConnectionStrings:DefaultConnection=Server=sqldata,1433;Database=aspnet-WebApplication3;User=sa;Password=Pass@word;Trusted_Connection=False;'
      - Pepper=qwsdfghjk
    ports:
      - 8080:80
    depends_on:
      - sqldata